### ISSUE TITLE
error with both scripts

### ISSUE THREAD

**Issue by itslemcy** [lechugalf/face-id#1]
hi, i get this error with both python scripts:

`Traceback (most recent call last):
  File "IdentifyFaces.py", line 53, in <module>
    main()
  File "IdentifyFaces.py", line 18, in main
    set_known_faces(sys.argv[2])
IndexError: list index out of range
`

could you help?

**Comment by lechugalf** [comment]
Hi, it's too late? 
Have you already passed the required arguments? as indicated in the README you need to pass the image to identify as the first argument and the directory of you recognized faces as the second argument. see the example. Indeed I should have put exceptions in the script. still getting the error? let me know please.
